import { Category } from '@/types'

// Categories for job classification (static data - safe for client components)
export const categories: Category[] = [
  {
    id: '1',
    name: 'EU Institutions',
    slug: 'eu-institutions',
    description: 'European Commission, Parliament, Council, and more',
    icon: '🏛️',
    longDescription: `EU Institutions are the backbone of European governance and policy-making. Working for the European Commission, European Parliament, Council of the EU, or the European Court of Justice places you at the heart of decisions that shape 450 million lives across 27 member states.\n\nRoles range from policy officers and translators to IT specialists and administrators. Most positions are based in Brussels, Luxembourg, or Strasbourg, with competitive salaries, generous benefits, and strong job security. The main recruitment channel is EPSO (European Personnel Selection Office), though contract agent and temporary positions are also regularly advertised.\n\nWhether you are a recent graduate looking for a Blue Book traineeship or a seasoned professional aiming for an AD-level official post, EU institutions offer diverse career paths in virtually every policy domain.`,
    salaryRange: '2,800 - 18,000/month (depending on grade AD5-AD16)',
    typicalRoles: ['Policy Officer', 'Legal Advisor', 'Administrator (AD)', 'Assistant (AST)', 'Contract Agent', 'Translator', 'IT Specialist', 'Communication Officer'],
    faqs: [
      { question: 'How do I get a job at an EU institution?', answer: 'The main route is through EPSO competitions, which include aptitude tests, competency assessments, and interviews. Contract agent positions (CAST) and temporary agent roles are also available and have shorter recruitment timelines.' },
      { question: 'What salary can I expect at an EU institution?', answer: 'EU officials earn between approximately 2,800 and 18,000 per month depending on their grade (AD5 to AD16). Salaries are tax-exempt from national taxation but subject to an EU community tax. Additional allowances for expatriation, dependants, and education are common.' },
      { question: 'Do I need to speak multiple languages?', answer: 'Yes, most positions require fluency in at least two EU official languages, with English, French, and German being the most commonly requested. Some roles, particularly translation and interpretation, require proficiency in three or more languages.' },
      { question: 'Where are EU institution jobs located?', answer: 'The majority of positions are in Brussels, Belgium. The European Parliament also has offices in Strasbourg, France, and Luxembourg. Some agencies and bodies are spread across EU member states.' },
      { question: 'What are the benefits of working for the EU?', answer: 'Benefits include competitive tax-advantaged salaries, expatriation allowance (up to 16% of base salary), generous annual leave (24+ days), a strong pension scheme, international school access for children, and excellent job security.' },
    ],
  },
  {
    id: '2',
    name: 'EU Agencies',
    slug: 'eu-agencies',
    description: 'EFSA, EMA, Frontex, and other EU agencies',
    icon: '🏢',
    longDescription: `EU agencies are decentralised bodies that support EU member states and their citizens. Over 40 agencies operate across Europe, each specialising in a specific policy area — from food safety (EFSA in Parma) to medicines regulation (EMA in Amsterdam) and border management (Frontex in Warsaw).\n\nAgency positions typically mirror EU institution grades but are often easier to access because they recruit directly rather than through EPSO competitions. Roles cover technical specialists, project managers, scientific assessors, data analysts, and administrative staff.\n\nWorking at an EU agency gives you deep expertise in a specific policy domain while enjoying similar benefits to EU institution staff, including competitive salaries, international working environments, and career development opportunities across the EU ecosystem.`,
    salaryRange: '2,500 - 14,000/month (grades FG I-IV, AD5-AD12)',
    typicalRoles: ['Scientific Officer', 'Project Manager', 'Data Analyst', 'Policy Expert', 'ICT Officer', 'Human Resources Officer', 'Finance Officer', 'Communication Specialist'],
    faqs: [
      { question: 'How are EU agency jobs different from EU institution jobs?', answer: 'EU agencies typically recruit directly rather than through EPSO competitions, making the process faster and more straightforward. They focus on specific technical or regulatory domains and are spread across EU member states rather than concentrated in Brussels.' },
      { question: 'Where are EU agencies located?', answer: 'EU agencies are spread across all member states. Major locations include Amsterdam (EMA), Parma (EFSA), Warsaw (Frontex), Dublin (Eurofound), Thessaloniki (CEDEFOP), Lisbon (EMCDDA), and many more.' },
      { question: 'What qualifications do I need for an EU agency role?', answer: 'Requirements vary by role and grade. Technical positions typically require a relevant university degree and several years of professional experience. Language requirements usually include excellent English plus one additional EU language.' },
      { question: 'Are EU agency salaries the same as EU institution salaries?', answer: 'EU agency salary scales generally follow the same structure as EU institutions but may have slight variations. Contract agents are graded FG I-IV, while temporary agents follow the AD/AST scale. Location-specific correction coefficients apply.' },
    ],
  },
  {
    id: '3',
    name: 'Trade Associations',
    slug: 'trade-associations',
    description: 'BusinessEurope, ETUC, and industry groups',
    icon: '🤝',
    longDescription: `Trade associations and industry federations represent business interests at the EU level. Brussels hosts hundreds of these organisations, from broad umbrella groups like BusinessEurope and the European Trade Union Confederation (ETUC) to sector-specific bodies covering everything from pharmaceuticals to renewable energy.\n\nJobs in trade associations combine policy expertise with stakeholder management, advocacy, and communications. You will track EU legislation, coordinate positions among member companies, organise events, and engage with EU institutions to shape policy outcomes.\n\nThese roles suit professionals who enjoy bridging the gap between industry and politics. Salaries are competitive with the private sector, and the work offers excellent networking opportunities and a front-row seat to EU decision-making.`,
    salaryRange: '3,000 - 10,000/month',
    typicalRoles: ['Policy Advisor', 'Government Affairs Manager', 'Director General', 'Communications Manager', 'Events Coordinator', 'Research Analyst', 'Membership Manager'],
    faqs: [
      { question: 'What does a trade association do in Brussels?', answer: 'Trade associations represent the collective interests of their member companies or industries before EU institutions. They monitor legislation, draft policy positions, organise events, and advocate for regulatory outcomes that benefit their sector.' },
      { question: 'What skills do I need for a trade association role?', answer: 'Key skills include strong knowledge of EU policy-making, excellent writing and analytical abilities, stakeholder management, event organisation, and often sector-specific expertise. Fluency in English is essential, with French often highly valued.' },
      { question: 'How much do trade association jobs pay in Brussels?', answer: 'Salaries typically range from 3,000 to 10,000 per month depending on seniority and the size of the organisation. Senior director positions at major associations can exceed this range.' },
      { question: 'Are trade association jobs good for career progression?', answer: 'Yes. Trade associations offer excellent exposure to EU policy, industry leaders, and institutional stakeholders. Many professionals use them as a stepping stone to senior roles in consultancies, companies, or EU institutions.' },
    ],
  },
  {
    id: '4',
    name: 'NGOs & Civil Society',
    slug: 'ngos',
    description: 'WWF, Greenpeace, Amnesty, and more',
    icon: '🌍',
    longDescription: `Brussels is one of the world\'s largest hubs for NGOs and civil society organisations operating at the European level. From global players like WWF European Policy Office, Greenpeace EU, and Amnesty International to specialised advocacy groups, hundreds of organisations work to influence EU policy on human rights, environment, health, development, and social justice.\n\nRoles in EU-focused NGOs are diverse: policy officers track and shape legislation, campaigners mobilise public support, fundraisers sustain operations, and communications professionals amplify the organisation\'s message.\n\nNGO jobs offer purpose-driven work and deep engagement with policy processes, though salaries are generally lower than the private sector. The sector values passion, expertise, and multilingual skills, and provides a meaningful career path for those committed to social impact.`,
    salaryRange: '2,200 - 7,000/month',
    typicalRoles: ['Policy Officer', 'Campaign Coordinator', 'Advocacy Manager', 'Fundraiser', 'Programme Manager', 'Communications Officer', 'Research Analyst'],
    faqs: [
      { question: 'What types of NGO jobs are available in Brussels?', answer: 'Brussels NGOs hire for policy and advocacy roles (tracking EU legislation, lobbying), communications (media relations, digital campaigns), programme management (coordinating EU-funded projects), fundraising, and research and analysis positions.' },
      { question: 'Do Brussels NGO jobs pay well?', answer: 'NGO salaries are typically lower than the private sector or EU institutions, ranging from 2,200 to 7,000 per month. However, many organisations offer good work-life balance, mission-driven work, and opportunities to influence European policy directly.' },
      { question: 'What background do I need for an NGO job in Brussels?', answer: 'Most roles require a relevant university degree (political science, law, environmental studies, etc.) and experience in the specific policy area. Languages (especially English and French) and EU policy knowledge are highly valued.' },
      { question: 'How do I find NGO jobs in Brussels?', answer: 'EUJobs.co regularly lists NGO vacancies. You can also check individual organisation websites, the European Civic Forum job board, and networks like the Social Platform or Green 10 alliance.' },
    ],
  },
  {
    id: '5',
    name: 'Think Tanks',
    slug: 'think-tanks',
    description: 'Bruegel, CEPS, EPC, and policy institutes',
    icon: '💡',
    longDescription: `Brussels is home to dozens of leading think tanks and policy research institutes that provide independent analysis to EU decision-makers. Organisations like Bruegel (economics), CEPS (Centre for European Policy Studies), the European Policy Centre (EPC), and Carnegie Europe produce research, policy briefs, and host events that shape the EU policy debate.\n\nThink tank roles combine academic rigour with policy relevance. Research fellows and analysts dive deep into specific policy areas, while communications teams disseminate findings to policymakers, media, and the public.\n\nThese positions suit intellectually curious professionals who want to bridge the gap between research and real-world policy impact. Many think tank professionals go on to roles in EU institutions, international organisations, or academia.`,
    salaryRange: '2,500 - 8,000/month',
    typicalRoles: ['Research Fellow', 'Policy Analyst', 'Programme Director', 'Communications Officer', 'Events Manager', 'Editor', 'Junior Researcher'],
    faqs: [
      { question: 'What is it like to work at a Brussels think tank?', answer: 'Think tank work combines academic-style research with real policy impact. You will write policy briefs, organise high-level events with EU officials, publish analysis, and engage with media. The pace is often fast, tied to the EU legislative calendar.' },
      { question: 'What qualifications do I need for a think tank position?', answer: 'Most research roles require a Master\'s degree or PhD in a relevant field (economics, political science, law, international relations). Strong analytical writing skills, policy knowledge, and publications track record are valued.' },
      { question: 'How much do think tank jobs pay in Brussels?', answer: 'Salaries range from approximately 2,500 per month for junior researchers to 8,000+ for senior fellows and directors. Think tanks generally pay less than consultancies but more than many NGOs.' },
      { question: 'Can think tank experience lead to EU institution jobs?', answer: 'Absolutely. Think tank experience is highly valued by EU institutions, and many professionals transition to policy roles in the European Commission, Parliament, or Council. The expertise and network built at a think tank are directly transferable.' },
    ],
  },
  {
    id: '6',
    name: 'Public Affairs & Lobbying',
    slug: 'public-affairs',
    description: 'Consultancies and in-house PA roles',
    icon: '📢',
    longDescription: `Public affairs is one of the most dynamic career sectors in Brussels. With the EU being the world\'s largest regulatory superpower, companies and organisations need professionals who can navigate the complex institutional landscape. The sector spans PA consultancies (like FleishmanHillard, Burson, and Hill+Knowlton), in-house government affairs teams at corporations, and specialised boutique firms.\n\nPublic affairs professionals monitor legislation, develop advocacy strategies, organise stakeholder coalitions, and engage with MEPs, Commission officials, and Council representatives. The work requires a blend of political savvy, strategic thinking, and strong communication skills.\n\nBrussels PA offers some of the highest private-sector salaries in the EU bubble, with excellent career progression. Consultancy roles are fast-paced and varied, while in-house positions offer deeper specialisation and often better work-life balance.`,
    salaryRange: '3,500 - 15,000/month',
    typicalRoles: ['Public Affairs Consultant', 'Government Affairs Director', 'Account Manager', 'Senior Advisor', 'Digital Advocacy Manager', 'Monitoring Analyst', 'Client Relations Manager'],
    faqs: [
      { question: 'What is public affairs in Brussels?', answer: 'Public affairs in Brussels involves helping organisations navigate and influence EU policy and regulation. This includes monitoring legislative developments, developing advocacy strategies, engaging with EU decision-makers, and building coalitions around policy positions.' },
      { question: 'How much do public affairs professionals earn in Brussels?', answer: 'Public affairs offers some of the highest private-sector salaries in Brussels, ranging from 3,500 per month for juniors to 15,000+ for senior directors. Consultancies and large corporations tend to pay at the higher end.' },
      { question: 'Do I need EU experience to work in public affairs?', answer: 'While EU institutional knowledge is highly valued, many professionals enter PA from journalism, law, political campaigns, or corporate communications. Consultancies often hire talented graduates and train them on EU affairs.' },
      { question: 'What is the difference between in-house and consultancy PA?', answer: 'Consultancies serve multiple clients across sectors, offering variety and fast learning. In-house roles focus on one company or industry, allowing deeper expertise and often better work-life balance. Both are well-paid and respected in Brussels.' },
    ],
  },
  {
    id: '7',
    name: 'Law Firms',
    slug: 'law-firms',
    description: 'EU law specialists and legal practices',
    icon: '⚖️',
    longDescription: `Brussels hosts numerous international and specialised law firms focusing on EU competition law, trade, regulatory affairs, and institutional law. Major international firms like Freshfields, Linklaters, and Covington maintain significant Brussels offices, alongside EU-specialist boutiques such as Van Bael & Bellis and Wilmer Cutler.\n\nLegal roles in Brussels EU law encompass competition/antitrust cases, trade defence (anti-dumping, sanctions), regulatory compliance (GDPR, AI Act, chemicals), and litigation before the EU courts. Brussels also hosts the bar\'s Conseil des Barreaux Europeens.\n\nFor lawyers, Brussels offers a unique practice environment where national, EU, and international law intersect. The work is intellectually challenging, internationally focused, and often high-profile, with salaries reflecting the demanding nature of the work.`,
    salaryRange: '4,000 - 20,000+/month',
    typicalRoles: ['Associate', 'Senior Associate', 'Partner', 'Legal Counsel', 'EU Competition Lawyer', 'Trade Lawyer', 'Regulatory Affairs Advisor', 'Paralegal'],
    faqs: [
      { question: 'What types of legal work are available in Brussels?', answer: 'Brussels legal work centres on EU competition law (mergers, antitrust, state aid), trade law (anti-dumping, sanctions), regulatory compliance (GDPR, AI Act, pharma regulation), EU institutional law, and public procurement. Both litigation and advisory work are common.' },
      { question: 'Do I need to be admitted to the Belgian bar?', answer: 'Foreign lawyers can practice EU law in Brussels by registering with the Brussels bar under the EU Establishment Directive. Many firms also hire lawyers qualified in other EU jurisdictions who work primarily on EU and international matters.' },
      { question: 'How much do EU lawyers earn in Brussels?', answer: 'Junior associates at international firms typically start around 4,000-6,000 per month, with senior associates earning 8,000-12,000. Partners and counsel at major firms can earn significantly more. Boutique firms may offer slightly lower salaries but comparable total packages.' },
      { question: 'Is Brussels a good place to build a legal career in EU law?', answer: 'Brussels is the global centre for EU law practice. Working here gives direct access to the European Commission, EU courts, and a vast network of EU law practitioners. It is the best location for building expertise in competition, trade, and regulatory law.' },
    ],
  },
  {
    id: '8',
    name: 'Media & Communications',
    slug: 'media',
    description: 'Politico, Euractiv, and EU media',
    icon: '📰',
    longDescription: `Brussels has a thriving media ecosystem covering EU politics and policy. Leading outlets include POLITICO Europe, Euractiv, the Brussels edition of Reuters and AFP, and specialist publications like MLex and PaRR. The European Commission and Parliament also maintain large press and communication departments.\n\nMedia and communications roles in the EU bubble span journalism (reporting on EU legislation, summits, and institutional politics), corporate communications (press releases, media relations), digital content creation, and institutional communication within EU bodies.\n\nThe sector values strong writing skills, policy knowledge, language abilities, and the ability to make complex legislation accessible. While journalism salaries can be modest, communications roles — especially in EU institutions or large consultancies — offer competitive packages.`,
    salaryRange: '2,500 - 10,000/month',
    typicalRoles: ['EU Correspondent', 'Press Officer', 'Communications Manager', 'Social Media Specialist', 'Editor', 'Content Strategist', 'Media Relations Manager', 'Spokesperson'],
    faqs: [
      { question: 'What media outlets are based in Brussels?', answer: 'Major EU-focused media include POLITICO Europe, Euractiv, The Brussels Times, and specialist outlets like MLex (competition law) and PaRR (regulatory risk). International outlets like Reuters, AFP, Bloomberg, and the Financial Times also maintain Brussels bureaux.' },
      { question: 'How can I get into EU journalism?', answer: 'Start by building EU policy knowledge and a portfolio of EU-related writing. Many journalists begin at smaller outlets like Euractiv or as freelancers, then move to larger publications. Language skills and understanding of EU institutions are essential.' },
      { question: 'What is the difference between journalism and communications roles?', answer: 'Journalists report independently on EU affairs for media outlets. Communications professionals work for institutions, companies, or consultancies to manage messaging and media relations. Communications roles typically pay more and are more numerous in Brussels.' },
      { question: 'Do media roles in Brussels require French?', answer: 'English is the primary working language for most EU media, but French is a significant advantage, especially for covering the European Parliament in Strasbourg or working with French-speaking institutions. Bilingual candidates are highly competitive.' },
    ],
  },
  {
    id: '9',
    name: 'International Organizations',
    slug: 'international-orgs',
    description: 'NATO, UN agencies, and more',
    icon: '🌐',
    longDescription: `Brussels and its surroundings host several major international organisations beyond the EU institutions. NATO headquarters is in Evere, while various UN agencies, the World Customs Organization, and other intergovernmental bodies maintain significant presences. These organisations offer careers at the intersection of diplomacy, defence, development, and international cooperation.\n\nInternational organisation jobs follow a structured grade system with competitive, tax-advantaged salaries. Roles range from political advisors and defence analysts at NATO to development specialists and programme officers at UN agencies.\n\nThese positions are highly international, with colleagues from dozens of nationalities. Recruitment is competitive but offers exceptional career development, international mobility, and the opportunity to work on global challenges from a European base.`,
    salaryRange: '3,500 - 16,000/month',
    typicalRoles: ['Political Advisor', 'Programme Officer', 'Defence Analyst', 'International Civil Servant', 'Project Manager', 'Budget Officer', 'Protocol Officer', 'Security Specialist'],
    faqs: [
      { question: 'What international organisations are based in Brussels?', answer: 'Key organisations include NATO (defence alliance), SHAPE (military command), various UN agencies (UNHCR, IOM liaison offices), the World Customs Organization, the ACP Secretariat, and Eurocontrol (air traffic management).' },
      { question: 'How do I apply for NATO jobs?', answer: 'NATO recruits through its official careers portal (nato.int/cps/en/natolive/recruit-main.htm). Positions are open to nationals of NATO member states. The recruitment process includes application screening, tests, interviews, and security clearance.' },
      { question: 'Are international organisation salaries tax-free?', answer: 'Most international organisations offer tax-advantaged salaries, either fully exempt from national tax or subject only to an internal tax system. The net salary is therefore typically higher than equivalent private-sector roles, though this varies by organisation.' },
      { question: 'What languages do I need for international organisation roles?', answer: 'English and French are the most commonly required languages. NATO uses English and French as official languages. UN agencies require at least two of their six official languages. Additional languages are always an asset.' },
    ],
  },
  {
    id: '10',
    name: 'Traineeships',
    slug: 'traineeships',
    description: 'Blue Book, Schuman, and internships',
    icon: '🎓',
    longDescription: `EU traineeships are the most popular gateway to a career in the Brussels bubble. The European Commission\'s Blue Book traineeship and the European Parliament\'s Schuman traineeship are the flagship programmes, each offering 5-month paid placements twice a year. EU agencies, the Council, and international organisations also run their own traineeship programmes.\n\nTraineeships provide hands-on experience in EU policy-making, excellent networking opportunities, and a strong foundation for building a European affairs career. Competition is fierce — the Blue Book programme receives over 15,000 applications for around 1,800 places per session.\n\nBeyond official EU programmes, hundreds of trade associations, NGOs, consultancies, and law firms in Brussels offer internships ranging from 3 to 12 months. While not all are paid, Belgian law increasingly requires fair compensation for interns.`,
    salaryRange: '1,200 - 1,400/month (EU institution traineeships)',
    typicalRoles: ['Blue Book Trainee', 'Schuman Trainee', 'Agency Trainee', 'Policy Intern', 'Communications Intern', 'Legal Intern', 'Research Intern'],
    faqs: [
      { question: 'What is the Blue Book traineeship?', answer: 'The Blue Book traineeship is the European Commission\'s flagship programme offering 5-month paid placements (approx. 1,400/month) in Brussels or Luxembourg. Two intakes per year (March and October) with about 1,800 places total. Applications open roughly 8 months before each session.' },
      { question: 'How competitive are EU traineeships?', answer: 'Very competitive. The Blue Book programme receives 15,000+ applications per session for approximately 900 places. The Schuman traineeship at the European Parliament is similarly competitive. Strong academic records, language skills, and relevant experience improve your chances significantly.' },
      { question: 'Do I need EU citizenship for a traineeship?', answer: 'EU citizenship is required for most Blue Book and Schuman traineeships, though a small number of places are reserved for non-EU nationals. Many NGOs, consultancies, and trade associations in Brussels accept interns regardless of nationality, subject to visa requirements.' },
      { question: 'Can a traineeship lead to a permanent EU job?', answer: 'While traineeships do not guarantee permanent employment, they are widely recognised as the best entry point to EU careers. Many former trainees go on to pass EPSO competitions or secure contract agent positions. The network and experience gained are invaluable.' },
      { question: 'When should I apply for EU traineeships?', answer: 'Blue Book applications typically open in January (for October start) and July (for March start). Schuman traineeship applications follow a similar cycle. Plan 6-12 months ahead and monitor the official EU traineeship portals for exact deadlines.' },
    ],
  },
]
